---
all:
        hosts:
                # if you had ungrouped hosts
                # describe them here
                # 10.10.2.2:
                # 10.10.1.1:
        children:
                planetexpress:
                        hosts:
                                bender:
                                        ansible_host: 10.10.2.3
                                        ansible_user: bender
                                fry:
                                        ansible_host: 10.10.2.4
                                        ansible_user: fry
                                zoidberg:
                                        ansible_host: 10.10.2.5
                                        ansible_user: zoidberg
                        vars:
                                dnsip: 8.8.8.8
                                ansible_python_interpreter: /usr/bin/python3
                arista_switches:
                        hosts:
                                sw-01:
                                        ansible_user: admin
                                sw-02:
                                        ansible_user: admin
